Vagrant.configure("2") do |config|

    config.vm.define "jenkins-k8s" do |ms|
        ms.vm.box = "sbeliakou/centos"
        ms.vm.hostname = "jenkins"
        ms.vm.provider "virtualbox" do |ms1|
            ms1.name = "jenkins-kubernetes-VM-Machine"
		  	ms1.memory = "4096"
        end
        ms.vm.network "private_network", ip: "192.168.56.225"
        ms.vm.provision "shell", path: "common.sh"
        ms.vm.provision "shell", path: "master.sh"
#        ms.vm.provision "shell", path: "jenkins.sh"
  	end

end
