---
# tasks file for jenkins
- block:
  - debug: var=java_vars_shell
  - name: install dependansis
    yum:
      name: 
        - fontconfig
        - dejavu-sans-fonts
      state: present

  - name: Download jenkins war    
    get_url:
      url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
      dest: '{{jenkins_home}}/jenkins.war' 
    become_user: jenkins
  - name: Start jenkins
    shell: |
      nohup /bin/java {{java_vars_shell}} -jar {{jenkins_home}}jenkins.war  &
    become_user: jenkins
  become: yes
- block:
  - template:
      src: proxy_pass.conf.j2
      dest: /etc/nginx/conf.d/proxy_pass.conf
    notify:
      - restart nginx
  become: yes
  when: configure_proxy_nginx
