
- name: creating jenkins_path
  file:
    path: "{{ jenkins_path }}"
    recurse: yes
    state: directory
  become: yes

- name: Add config file
  become: yes
  template: 
    src: template/config.j2
    dest: "{{ jenkins_path }}config"


- name: Download jenkins.war
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: "{{ jenkins_path }}"
  become: yes 

- name: creating config file
  file:
    path: "{{ jenkins_path }}config"
    state: touch
  become: yes

- name: Add jenkins.service file
  template:
    src: template/jenkins.service.j2
    dest: /usr/lib/systemd/system/jenkins.service
  become: yes
  notify: restart jenkins

- name: systemctl daemon reload
  systemd:
    daemon_reload: yes
  become: yes
  
- name: Allow port 8080
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "8080"
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
  become: yes

- name: Start jenkins server
  systemd:
    name: jenkins
    state: started
    enabled: yes
  become: yes
