- hosts: jenkins
  vars:
    user: root
    source_files: "templates/jenkins/*yml.j2"
  tasks:
    - block:
      - debug: var=source_files
      - file:
          path: /tmp/jenkins
          state: directory
      - template:
          src: "{{ item }}"
          dest: /tmp/jenkins
          owner: "{{user}}"
          group: "{{user}}"
        register: files 
        with_fileglob: "{{ source_files }}"
      - debug: var=files.results
      - shell: |
          kubectl create ns jenkins
      - name: jenkinsInit
        shell: |
          kubectl apply -f "{{ item.dest }}" -n jenkins
        with_items: "{{ files.results }}"
      - name: jenkinsDestroy
        shell: |
          kubectl delete -f "{{ item.dest }}" -n jenkins
        with_items: "{{ files.results }}"
        tags:
          - never
          - destroy
      become: yes
      become_user: "{{ user }}"
     
