Vagrant.configure("2") do |config|
  config.vm.define "master" do |m1|
    m1.vm.box = "sbeliakou/centos"
    m1.vm.network :private_network, ip: "192.168.56.225"
    m1.vm.hostname = "master"
    m1.ssh.insert_key = false
    m1.vm.provider "virtualbox" do |vb|
      vb.name = "master"
      vb.memory = "4096"
      end
    m1.vm.provision "shell", path: "docker.sh"
    m1.vm.provision "shell", path: "2_1.sh"
    m1.vm.provision "shell", path: "2_4.sh"
    m1.vm.provision "shell", path: "3_1.sh"

  end
  config.vm.define "worker" do |m2|
    m2.vm.box = "sbeliakou/centos"
    m2.vm.network :private_network, ip: "192.168.56.226"
    m2.vm.hostname = "worker"
    m2.ssh.insert_key = false
    m2.vm.provider "virtualbox" do |vm|
      vm.name = "worker"
      vm.memory = "4096"
      end
    m2.vm.provision "shell", path: "docker.sh"
    m2.vm.provision "shell", path: "2_1.sh"
    m2.vm.provision "shell", path: "worker_join.sh"

  end

end

