
- name: install deltarpm
  yum:
    name: deltarpm
    state: latest
    
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install epel and other tools
  yum:
    name: 
    - epel-release
    - wget
    - ntp
    - jq
    - net-tools
    - bind-utils
    - moreutils
    - git
    - bash-completion
    state: latest

- name: start ntpd
  service:
    name: ntpd
    enabled: yes
    state: started

- name: Disable SELinux
  selinux:
    state: disabled

- name: disable swap
  shell: |
    sed -i '/swap/d' /etc/fstab

- name: swapoff
  shell: |
    swapoff --all