apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      volumes:
      - name: jhome
        emptyDir: {}
      containers:
      - name: master
        image: jenkins/jenkins:lts
        volumeMounts:
        - name: jhome
          mountPath: /var/jenkins_home
        ports:
        - containerPort: 8080
        - containerPort: 50000
