apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - jenkins
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/jenkins

# kubectl apply -f /vagrant/volumes/jenkins_pv.yaml
# persistentvolume/localvolume-pv created