---
# handlers file for user
- name: save user details
  copy: 
    content: >
      {
        "Croup name": "{{ group_name }}",
        "User name": "{{ user_name }}",
        "Gid": "{{ group_guid }}",
        "Uid": "{{ users_uid[user_name] }}",
        "Sudoriers": "{{ user_priv }}",
        "Time created": "{{ ansible_date_time.iso8601 }}"
      }
    dest: "{{ '/etc/ansible/facts.d/user_' + user_name + '.fact' }}"
  become: yes