- name: New group
  become: yes
  group:
    name: "{{ user_group }}"
    gid: "{{ group_id }}"
    state: present

- name: New groups
  become: yes
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ user_groups }}"
  when: user_groups is defined

- name: New user
  become: yes
  user:
    name: "{{ user_name }}"
    uid: "{{ user_id }}"
    comment: "{{ user_comment }}"
    group: "{{ user_group }}"
    groups: "{{ user_groups }}"
    home: "{{ user_home }}"
    create_home: "{{ create_home }}"

#- name: Add key
#  become: yes
#  authorized_key:
#    user: "{{ user_name }}"
#    state: present
#    key: "{{ item }}"
#  with_items: "{{ authorized_keys }}"
#  when: authorized_keys is defined

#- name: Add sudoers
#  become: yes
#  copy:
#    content: "{{ sudoers }}"
#    dest: /etc/sudoers.d/{{ user_name }}
#    validate: /usr/sbin/visudo -cf %s
#    backup: yes
#  when: sudoers != ""

- name: Directory for facts
  become: yes
  file:
    path: /etc/ansible/facts.d
    state: directory
    mode: 0755

- name: Create fact
  become: yes
  template:
    src: user_fact.j2
    dest: /etc/ansible/facts.d/user_{{ user_name }}.fact

