- name: Install httpd
  yum:
    name: httpd
    state: present
  become: yes

- name: configure httpd
  copy: 
    src: hello.conf
    dest: /etc/httpd/conf.d/
  become: yes
    
- name: run service
  service: 
    name: httpd
    enabled: yes
    state: started
  become: yes

