Vagrant.configure("2") do |config|
  config.vm.define "server" do |m1|
    m1.vm.box = "sbeliakou/centos"
    m1.vm.network :private_network, ip: "1.2.3.4"
    m1.vm.hostname = "server"
    m1.ssh.insert_key = false
    m1.vm.provider "virtualbox" do |vb|
      vb.name = "server"
      vb.memory = "4096"
      end
    m1.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
  end
end
end
